pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: "*/${params.branch}"]], userRemoteConfigs: [[url: 'https://github.com/hamidhosseini31397/TrailrunnerJenkins.git']]])
            }
        }

        stage('Build') {
            steps {
                sh "mvn compile"
            }
        }

        stage('Test') {
            steps {
                sh "mvn test"
            }
        }

        stage('Post Test') {
            steps {
                script {
                    jacoco(
                        execPattern: 'target/*.exec',
                        classPattern: 'target/classes',
                        sourcePattern: 'src/main/java',
                        exclusionPattern: 'src/test*'
                    )
                    junit '**/TEST*.xml'
                } 
            }
        }

        stage('Run Robot') {
            steps {
                dir('C:/Users/hamhos/.jenkins/workspace/JenkinsLab2024/Selenium') {
                    // Run the robot command to execute all .robot files
                    bat "python -m robot labSelenium.robot"
                }
            }
            
            post {
                always {
                    // Post-processing steps for Robot Framework reports
                    robot outputPath: 'C:/Users/hamhos/.jenkins/workspace/JenkinsLab2024/Selenium', passThreshold: 80.0, unstableThreshold: 70.0, onlyCritical: false
                }
            }
        }

        // Additional stages in your pipeline
    }
}
